apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::324874112366:role/eksctl-expense-cluster-nodegroup-e-NodeInstanceRole-tb8YIJ9jfMda
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::111122223333:user/admin
      username: suresh    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-24T11:55:56Z"
  name: aws-auth
  namespace: kube-system
  #resourceVersion: "1313"ewewewew
  uid: 16e76cb0-38a1-4fc3-a89a-291a3dc12d84
